name = "Jutul"
uuid = "2b460a1a-8a2b-45b2-b125-b5c536396eb9"
version = "0.4.16"
authors = ["Olav MÃ¸yner <olav.moyner@gmail.com>"]

[deps]
AlgebraicMultigrid = "2169fc97-5a83-5252-b627-83903c6c433c"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
ILUZero = "88f59080-6952-5380-9ea5-54057fb9a43f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
Metis = "2679e427-3c69-5b7f-982b-ece356f1e94b"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
PolyesterWeave = "1d0040c9-8b98-4ee7-8388-3f51789ca0ad"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseConnectivityTracer = "9f842d2f-2579-4b1d-911e-f412cf18a3f5"
SparseMatrixColorings = "0a514795-09f3-496d-8182-132a7b665d35"
SparsityTracing = "06eadbd4-12ad-4cbc-ab6e-10f8370940a5"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SymRCM = "286e6d88-80af-4590-acc9-0001b223b9bd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[weakdeps]
AMGCLWrap = "4f76b812-4ba5-496d-b042-d70715554288"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
HYPRE = "b5ffcf37-a2bd-41ab-a3da-4bd9bc8ad771"
KaHyPar = "2a6221f6-aa48-11e9-3542-2d9e0ef01880"
LBFGSB = "5be7bae1-8223-5378-bac3-9e7378a2f6e6"
LayeredLayouts = "f4a74d36-062a-4d48-97cd-1356bad1de4e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"
PartitionedArrays = "5a9dfac6-5c52-46f7-8278-5e2210713be9"

[extensions]
JutulAMGCLWrapExt = "AMGCLWrap"
JutulGLMakieExt = "GLMakie"
JutulGmshExt = "Gmsh"
JutulGraphMakieExt = ["GraphMakie", "NetworkLayout", "LayeredLayouts", "Makie"]
JutulHYPREExt = "HYPRE"
JutulKaHyParExt = "KaHyPar"
JutulLBFGSBExt = "LBFGSB"
JutulMakieExt = "Makie"
JutulPartitionedArraysExt = ["PartitionedArrays", "MPI"]

[compat]
AMGCLWrap = "=0.3.2"
AlgebraicMultigrid = "0.5.1"
Crayons = "4.1.1"
DataStructures = "0.18.13"
DifferentiationInterface = "0.7.0"
ExprTools = "0.1.8"
ForwardDiff = "0.10.30, 1"
GraphMakie = "0.5.3"
Graphs = "1.8.0"
HYPRE = "1.8"
ILUZero = "0.2.0"
JLD2 = "0.4, 0.5, 0.6"
KaHyPar = "0.3.0"
Krylov = "0.9.1"
LBFGSB = "0.4.1"
LayeredLayouts = "0.2.5"
LinearOperators = "2.3.2"
LoopVectorization = "0.12.115"
MAT = "0.10.3, 0.11"
Makie = "0.21, 0.22, 0.23, 0.24"
MappedArrays = "0.4.1"
Metis = "1.1.0"
NetworkLayout = "0.4.5"
OrderedCollections = "1.4.1"
Polyester = "0.6.11, 0.7.3"
PolyesterWeave = "0.1.13, 0.2.1"
Polynomials = "3 - 4"
PrettyTables = "2.0"
ProgressMeter = "1.7.2"
SparseConnectivityTracer = "1"
SparseMatrixColorings = "0.4.19"
SparsityTracing = "0.2.4"
StaticArrays = "1.5.17"
Statistics = "1"
SymRCM = "0.2.1"
TimerOutputs = "0.5.19"
Tullio = "0.3.4"
julia = "1.7"

[extras]
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
HYPRE = "b5ffcf37-a2bd-41ab-a3da-4bd9bc8ad771"
KaHyPar = "2a6221f6-aa48-11e9-3542-2d9e0ef01880"
LBFGSB = "5be7bae1-8223-5378-bac3-9e7378a2f6e6"
LayeredLayouts = "f4a74d36-062a-4d48-97cd-1356bad1de4e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"
PartitionedArrays = "5a9dfac6-5c52-46f7-8278-5e2210713be9"

[targets]
test = ["KaHyPar", "HYPRE", "LBFGSB"]
